<script type='text/javascript'>
  var nagvis_current_map = '<?= $map ?>';

  function nagvis_frame_reload(){
    // When iframe reloaded, take map name from iframe URL and add it as GET parameter to main URL
    var fr = document.getElementById('nagvis_frame');
    var regex = new RegExp("[\\?&]show=([^&#]*)");
    var results = regex.exec(fr.contentWindow.location);
    if (results!=null) {
      var map = results[1];
      if (map != nagvis_current_map) {
        this.history.pushState({icinga: true}, null, 'nagvis?map=' + map);
        nagvis_current_map = map;
      }
    } else {
      this.history.pushState({icinga: true}, null, 'nagvis');
      nagvis_current_map = '';
    }
  };

</script>

<iframe id=nagvis_frame src="<?= $this->url ?>frontend/nagvis-js/index.php<?= $map_get ?>"  style="margin-bottom: -10px;" width=100% height=100% marginheight=0 marginwidth=0 wspace=0  frameborder=0 onload="nagvis_frame_reload();">
</iframe>
